server:
  port: 8888

spring:
  config:
    name: configserver
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        git:
          uri: C:\\Users\\ohunko\\Home\\config-repo\\
